### ISSUE TITLE
Domain toString 변경 요청

### ISSUE THREAD

**Issue by yang-jihoon** [HyunWooo/hwst#1]
domain object 보면 tostring을 선언해 놓았는데~
용도가 데이터를 확인하는 용도라면~ 변수를 열거하는 것 말고~
포함되어 있는 변수를 전체 출력하는 효율적인 다른 방법이 있습니다. ^^

한번 알아보고 적용해 보세요~

**Comment by HyunWooo** [comment]
매니저님! 말씀을 드렸어야했는데 죄송합니다.
아마 지난주 목요일날 매니저님께 말씀드리려다가 휴가가시고 저도 코딩테스트공부만 하다가 
깜빡 잊은것 같습니다...
요청주신것들 수정해보았으며, 검토 부탁드립니다.

리팩토링 하는것들을 
http://kms.mgt.11st.co.kr/pages/viewpage.action?pageId=11141216
에 따로 정리해보고 있으니 혹시나 뭘 바꾼거지 찾기 어려우시다면 참고하셔도 될 것 같습니다.
바쁘실텐데 신경써주셔서 감사합니다!!

**Comment by yang-jihoon** [comment]
잘했어요~ 완료된것은 close 해주세요~ ㅎ
